googleapis/java-datastore

- google-cloud-datastore/src/test/java/com/google/cloud/datastore/ITDatastoreTest.java
- google-cloud-datastore/src/test/java/com/google/cloud/datastore/testing/ITLocalDatastoreHelperTest.java
Integration tests are not ran on OS X CI builds, moving DatastoreTest &
LocalDatastoreHelperTest to work around the fact that the emulator is
accessible on kokoro nodes.
> chore(test): rename DatastoreTest to ITDatastoreTest

- google-cloud-datastore-bom/pom.xml
The bom had been miss configured to change the version of google-cloud-datastore to be the version for proto-google-cloud-datastore-v1 this change fixes the marker and the version.
> fix: bom version tag miss configured

- google-cloud-datastore/clirr-ignored-differences.xml
- google-cloud-datastore/src/main/java/com/google/cloud/datastore/Datastore.java
- google-cloud-datastore/src/main/java/com/google/cloud/datastore/DatastoreImpl.java
- google-cloud-datastore/src/main/java/com/google/cloud/datastore/spi/v1/DatastoreRpc.java
- google-cloud-datastore/src/main/java/com/google/cloud/datastore/spi/v1/HttpDatastoreRpc.java
- google-cloud-datastore/src/test/java/com/google/cloud/datastore/ITDatastoreTest.java
- google-cloud-datastore/src/test/java/com/google/cloud/datastore/it/ITDatastoreTest.java
Fixes #53 
Proposed Design [Doc](https://docs.google.com/document/d/1FYfg3-R6-AoWbv5JWlYoJYtG-L-JpQCpISy3IVDBpK0/edit#).
~/cc: @BenWhitehead
> feat: expose reserveIds API

- google-cloud-datastore/src/test/java/com/google/cloud/datastore/it/ITDatastoreTest.java
- google-cloud-datastore/src/test/java/com/google/cloud/datastore/it/MultipleAttemptsRule.java
- google-cloud-datastore/src/test/java/com/google/cloud/datastore/it/MultipleAttemptsRuleTest.java
Datastore (when not Firestore in Datastore mode) is eventually
consistent. Sometimes this means queries may not show the expected
results within the short timespan of a test. This change adds a new
JUnit Rule - MultipleAttemptsRule - which allows tests to attempt to
succeed up to three times. If a test is unable to pass within the 3
allowed attempts, the errors from each attempt will be returned as an
overall failure.
Fixes #97
Fixes #101
> test: update ITDatastoreTest test to attempt multiple times if a test fails

- google-cloud-datastore/src/main/java/com/google/cloud/datastore/DatastoreImpl.java
- google-cloud-datastore/src/main/java/com/google/cloud/datastore/TransactionOperationExceptionHandler.java
- google-cloud-datastore/src/test/java/com/google/cloud/datastore/ITDatastoreTest.java
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
Fixes b/157596445 ☕️
Add a new exception handler for requests that may run within a transaction. The handler prevents retries on ABORTED error, since an aborted transaction cannot be re-used.
> fix: update retry logic for operations that can be associated with a transaction

- google-cloud-datastore/src/main/java/com/google/cloud/datastore/testing/LocalDatastoreHelper.java
- google-cloud-datastore/src/test/java/com/google/cloud/datastore/testing/ITLocalDatastoreHelperTest.java
> feat: add support to customize gcloud command of LocalDatastoreHelper

- google-cloud-datastore/pom.xml
- google-cloud-datastore/src/main/java/com/google/cloud/datastore/DatastoreImpl.java
- google-cloud-datastore/src/main/java/com/google/cloud/datastore/TraceUtil.java
- google-cloud-datastore/src/main/java/com/google/cloud/datastore/spi/v1/HttpDatastoreRpc.java
- pom.xml
> feat: add opencensus tracing/stats support

- pom.xml
Rather than having a direct managed dependency for
google-auth-library-oauth2-http use the version provided by
google-cloud-shared-dependencies.
> deps: remove direct declaration of google-auth-library-oauth2-http

- .github/CODEOWNERS
- .repo-metadata.json
- synth.metadata
CODEOWNERS is now managed by templates and we can configure the default team in the .repo-metadata.json file.
> chore: regenerate CODEOWNERS from templates

- pom.xml
to address Data Fusion customer issue where they need compatibility for datastore, bigquery, pubsub, storage, texttospeech, and bigtable client libraries.
> deps: update google-cloud-shared-dependencies to 0.15.0

- README.md
> fix(docs): broken links

- google-cloud-datastore-bom/pom.xml
All java client libraries inherit the distributionManagement section form shared-config. To prevent individual pom files from overriding the shared-config version of distributionManagement, it is being removed.
> chore: remove distributionManagement section

- pom.xml
It is managed in the shared dependencies BOM
> deps: update shared dependencies to 2.7.0 and remove google-oauth-client from dependency management

- google-cloud-datastore/src/main/java/com/google/cloud/datastore/GqlQuery.java
- google-cloud-datastore/src/main/java/com/google/cloud/datastore/ReadOption.java
- google-cloud-datastore/src/main/java/com/google/cloud/datastore/ValueType.java
- google-cloud-datastore/src/test/java/com/google/cloud/datastore/ValueTest.java
ImmutableMap.Builder.build() recommends usage of buildOrThrow() instead.
> fix: Use ImmutableMap.Builder.buildOrThrow() instead of build().

- samples/native-image-sample/README.md
- samples/native-image-sample/pom.xml
- samples/native-image-sample/src/main/java/com/example/datastore/NativeImageDatastoreSample.java
- samples/native-image-sample/src/test/java/com/example/datastore/ITNativeImageDatastoreSample.java
- samples/pom.xml
This PR copies over the Datastore sample, Setup Instructions and README for native image support from [GoogleCloudPlatform/native-image-support-java](https://github.com/GoogleCloudPlatform/native-image-support-java/tree/master/native-image-samples/native-image-samples-client-library/datastore-sample). Some things note:
1. It adds an integration test that can be run as a native image.
2. It slightly modifies the output of the sample to be more readable. 
Calling `mvn package -Pnative` builds the native image for the application and calling `mvn test -Pnative` runs the test as a native image. 
For more information: https://graalvm.github.io/native-build-tools/latest/maven-plugin.html#configuration
> docs(sample): Add sample for native image support in Datastore

- README.md
- samples/native-image-sample/pom.xml
This fixes the following failure in the nightly samples build:
If you write sample code, please follow the [samples format](
https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/SAMPLE_FORMAT.md).
> docs(sample): Use Java 8 for Native Image sample

- README.md
- pom.xml
This introduces use of the errorprone plugin as described at https://errorprone.info/docs/installation#maven. The warnings can then be addressed, `@SuppressWarnings(…)`ed, or if desired, have entire classes of warnings turned off. Then once the codebase is clean, the warnings can be treated as errors. This will reduce the drift between github and the monorepo, which generally tries to enforce errorprone cleanliness.
Related to #590.
> style: Add errorprone warnings.

- datastore-v1-proto-client/src/main/java/com/google/datastore/v1/client/DatastoreHelper.java
> docs: update doc link

- .github/CODEOWNERS
- .repo-metadata.json
- README.md
* chore: Change the Codeowner to cloud-native-db-dpes
* 🦉 Updates from OwlBot post-processor
See https://github.com/googleapis/repo-automation-bots/blob/main/packages/owl-bot/README.md
* Add api-firestore team
* Update CODEOWNERS
* 🦉 Updates from OwlBot post-processor
See https://github.com/googleapis/repo-automation-bots/blob/main/packages/owl-bot/README.md
* Add @googleapis/api-firestore to the codeowner
* 🦉 Updates from OwlBot post-processor
See https://github.com/googleapis/repo-automation-bots/blob/main/packages/owl-bot/README.md
Co-authored-by: Owl Bot <gcf-owl-bot[bot]@users.noreply.github.com>
cherry pick of #686
> chore: Change the Codeowner to cloud-native-db-dpes (#686)

- datastore-v1-proto-client/src/main/java/com/google/datastore/v1/client/DatastoreHelper.java
* Constructors and methods with the same name should appear sequentially with no other code in between.
* This catch block catches an exception and re-throws another, but swallows the caught exception rather than setting it as a cause. This can make debugging harder.
Courtesy of clshepherd/clrobot in the monorepo.
Fixes #590.
> style: Fix 2 ErrorProneStyle findings

- samples/snippets/src/test/java/com/google/datastore/snippets/ConceptsTest.java
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
Fixes #<issue_number_goes_here> ☕️
Java samples do not use transaction but rest of the languages do
Link to Example:
https://cloud.google.com/datastore/docs/concepts/entities#update_an_entity
If you write sample code, please follow the [samples format](
https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/SAMPLE_FORMAT.md).
> fix(sample): change update entity sample to use transaction
